name: Build

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build linux
        run: make linux-amd64
      - name: Build darwin
        run: |
          OS=darwin ARCH=amd64 make darwin-amd64
      - name: Build windows
        run: |
          OS=windows ARCH=amd64 make windows-amd64
