name: E2E Test

on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch: { }

jobs:
  build-artifact:
    env:
      VELAUX_VERSION_KEY: github.com/oam-dev/velad/version.VelaUXVersion
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build linux amd64
        run: |
          OS=linux ARCH=amd64 make linux-amd64
      - name: Build linux arm64
        run: |
          OS=linux ARCH=arm64 make linux-arm64
      - name: Build darwin
        run: |
          OS=darwin ARCH=amd64 make darwin-amd64
      - name: Build windows
        run: |
          OS=windows ARCH=amd64 make windows-amd64
      - name: Upload linux amd64 artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/velad-linux-amd64
          name: velad-linux-amd64
      - name: Upload linux arm64 artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/velad-linux-arm64
          name: velad-linux-arm64
      - name: Upload darwin artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/velad-darwin-amd64
          name: velad-darwin-amd64
      - name: Upload windows artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/velad-windows-amd64
          name: velad-windows-amd64
  test-linux:
    runs-on: ubuntu-20.04
    needs: [ build-artifact ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: velad-linux-amd64
      - run: chmod u+x velad-linux-amd64 && mv velad-linux-amd64 velad
      - run: sudo ./velad install
      - run: sudo vela def list
  test-darwin:
    runs-on: macos-12
    needs: [ build-artifact ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: velad-darwin-amd64
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      - run: chmod u+x velad-darwin-amd64 && mv velad-darwin-amd64 velad
      - run: ./velad install
      - run: vela def list
#  test-linux-arm64:
#    runs-on: ubuntu-20.04
#    needs: [ build-artifact ]
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: velad-darwin-amd64
#      - run: chmod u+x velad-linux-amd64 && mv velad-linux-amd64 velad
#      - name: pguyot/arm-runner-action@v2
#        with:
#          commands: |
#            sudo ./velad install
#            sudo vela def list

#  test-windows:
#    runs-on: windows-2022
#    needs: [ build-artifact ]
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: velad-windows-amd64
#      - name: Setup Docker
#        uses: docker-practice/actions-setup-docker@master
#      - run: chmod u+x velad-windows-amd64 && mv velad-windows-amd64 velad.exe
#      - run: .\velad install

